[project]
name = "rag-agent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "faiss-cpu>=1.15.1",
    "ipykernel>=7.4.0",
    "langchain>=1.4.3",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.7",
    "langchain-text-splitters>=1.1.2",
    "pandas>=3.0.6",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "python-env>=1.0.0",
]
