[project]
name = "rag-agent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "docling-core[chunking-openai]>=2.99.0",
    "docling-ibm-models>=4.0.3",
    "docling-slim[format-pdf-docling]>=2.133.0",
    "dotenv>=0.9.9",
    "faiss-cpu>=1.15.1",
    "ipykernel>=7.4.0",
    "ipywidgets>=8.1.9",
    "langchain>=1.4.3",
    "langchain-chroma>=1.1.0",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-docling>=3.0.0",
    "langchain-openai>=1.6.7",
    "langchain-text-splitters>=1.1.2",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "python-env>=1.0.0",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
]
